name: life_line_ngo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.2.1
  just_audio: ^0.10.5
  appwrite: ^14.0.0
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  flutter_riverpod: ^3.3.1
  envied: ^0.5.4

  #For OpenStreetMap
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1


dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^0.5.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/offline_logos/
    - assets/images/
    - assets/fonts/
    - assets/audio/
  
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
    - family: OpenSansVariable
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
